server {
    listen 80;
    listen [::]:80;
    server_name wiki.mineraltown.net mineraltown.net;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name wiki.mineraltown.net mineraltown.net;
    charset utf-8;

    http2 on;

    ssl_certificate /etc/ssl/mineraltown.net/fullchain.pem;
    ssl_certificate_key /etc/ssl/mineraltown.net/privkey.pem;
    add_header Strict-Transport-Security "max-age=63072000" always;
    server_tokens off;

    root /var/www/wiki;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name api.mineraltown.net;
    charset utf-8;

    server_tokens off;

    http2 on;

    ssl_certificate /etc/ssl/mineraltown.net/fullchain.pem;
    ssl_certificate_key /etc/ssl/mineraltown.net/privkey.pem;
    add_header Strict-Transport-Security "max-age=63072000" always;

    location / {
        include uwsgi_params;
        uwsgi_pass   unix:///var/www/wiki-server/wiki.sock;
    }

    client_max_body_size 100M;
    location = /favicon.ico {
        log_not_found off;
        access_log off;
        root /var/www/wiki/static/favicon;
    }

    location /static {
        alias /var/www/wiki-server/static;
    }

    location /media {
        alias /var/www/wiki-server/media;
    }
}